version: "2"
services:
  app:
    build: flask-app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    container_name: "postgres"
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'dms_db'
    volumes:
    - ./db:/docker-entrypoint-initdb.d #/:ro
