version: "3"
services:
  dms_server:
    build: flask-app
    command: python app.py
    links:
      - flask_db
    ports:
      - "5000:5000"
    depends_on:
      - flask_db

  flask_db:
    #container_name: "flask_db"
    image: postgres
    restart: always
    ports:
    - "5431:5432"
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'dms_db'
    volumes:
    - ./data:/var/lib/postgresql/data/
    - ./db:/docker-entrypoint-initdb.d/:ro
