version: "3"
services:
  dms_server:
    restart: always
    build: flask-app
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - flask_db
  grafana_server:
    restart: always
    build: grafana-app
    command: python app.py
    #ports:
    #  - "6000:5000"
    depends_on:
      - flask_db
  grafana_ui:
    restart: always
    build:
      context: .
      dockerfile: ./grafana-ui/Dockerfile
      args:
        GRAFANA_VERSION: 6.7.2
        GF_INSTALL_PLUGINS: grafana-simple-json-datasource, flant-statusmap-panel, michaeldmoore-multistat-panel #,grafana-clock-panel
    restart: always
    environment:
      GF_SERVER_ROOT_URL: ${ROOT_URL}
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: mail_service:25
      GF_SMTP_USER: ${GMAIL_USER}
      GF_SMTP_PASSWORD: ${GMAIL_PASSWORD}
    user: "104"
    depends_on:
      - grafana_server
      - flask_db
    ports:
      - "3000:3000"
    volumes:
    # - ./mount/grafana:/var/lib/grafana
     - grafana-storage:/var/lib/grafana
  mail_service:
    image: namshi/smtp:latest
    environment:
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
  flask_db:
    image: postgres:12.0
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dms
    volumes:
     - ./mount/data:/var/lib/postgresql/data/
    # - ./db:/docker-entrypoint-initdb.d/:ro
  liqui:
    depends_on:
      - flask_db
    build:
      context: .
      dockerfile: ./liquibase/Dockerfile
    links:
      - flask_db
volumes:
  grafana-storage:
